### ISSUE TITLE
Possible Enchants Don't Appear in Uses in JEI

### ISSUE THREAD

**Issue by MuteTiefling** [ToMe25/Botania-Additions#1]
I don't know if this is actually something you have any control over, but JEI does not show what enchants can be used on the Terra Bow. It does accept Power, and I'm assuming others that make sense.

Mod Version: BotaniaAdditionsMC1.16.3-1.0.1

**Comment by ToMe25** [comment]
I will look into fixing this later today.

> It does accept Power, and I'm assuming others that make sense.

It accepts Unbreaking, Power, Punch, Flame, Infinity, Mending, and Curse of Vanishing because of how botania handles enchanments, even tho Unbreaking, Infinity, and Mending make no sense.

**Comment by ToMe25** [comment]
This should be fixed in version 1.0.2 that is now public on curseforge.

Thanks for reporting the issue :)
