### ISSUE TITLE
[1.16.3] Disabling Terra Harvester prevents starting the game

### ISSUE THREAD

**Issue by NielsPilgaard** [ToMe25/Botania-Additions#2]
Setting the config `enableTerraHarvester` to `false` prevents the game from starting.

Latest.log: https://gist.github.com/NillerMedDild/5ab17df00d4bfdc15067d40ff3f3cd57

`BotaniaAdditionsMC1.16.3-1.0.2`

**Comment by ToMe25** [comment]
Sorry, i never had issues like that with my other mods, so i only tested that in 1.14, and not in 1.16, if i can reproduce this i will fix it later today.

**Comment by NielsPilgaard** [comment]
No worries, these things happen :)

**Comment by ToMe25** [comment]
The new version 1.0.3 that is now public on curseforge fixes this.

**Comment by NielsPilgaard** [comment]
Thanks!
