### ISSUE TITLE
Terra Harvester Crash

### ISSUE THREAD

**Issue by WenXin20** [ToMe25/Botania-Additions#7]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Botania v410`
`Botania Additions v1.0.3`
 
I was in creative trying out the Terra Harvester when I broke a tall grass plant but crashed instead.
[Crash Report](https://gist.github.com/WenXin20/a6b01fd40db00fc0b31bbf1d9c49697b)

**Comment by ToMe25** [comment]
This crash is due to a change in botania.
I remember seeing that method getting changed, but it seems like i forgot to change how Botania Additions handles that.
This will hopefully be fixed tomorrow.

**Comment by ToMe25** [comment]
Should be Fixed in version 1.16.4-1.0.4, now approved on CurseForge.

**Comment by WenXin20** [comment]
Thanks!
